yas_marina_mro.xml=Yas Marina,180,false
albert_park_mro.xml=Albert Park,140,true
singapura_mro.xml=Singapura,180,false
monza_mro.xml=Monza,180,false
montecarlo_mro.xml=Monte Carlo,140,false
interlagos_mro.xml=Interlagos,160,true
silverstone_mro.xml=Silverstone,180,false
indianapoles_mro.xml=Indianapoles,180,false
montreal_mro.xml=Montreal,180,false
magny_mro.xml=Magny-Cours,180,false
suzuka_mro.xml=Suzuka,160,false
hockenheim_mro.xml=Hockenheim,180,false
hockenheim6601_mro.xml=Hockenheim6601,160,false
spa_mro.xml=Spa-Francorchamps,150,false
hungaro_ring_mro.xml=Hungaro Ring,180,false
catalunya_mro.xml=Catalunya,160,true
bahrain_mro.xml=Bahrain,150,false
spang_mro.xml=Sepang,150,false
shangai_mro.xml=Shangai,150,false
jerez_mro.xml=Jerez,140,false
donington_mro.xml=Donington,150,false
istambul_mro.xml=Istanbul Park,180,false
estoril_mro.xml=Estoril,180,false
imola_mro.xml=Imola,170,false
valencia_mro.xml=Valencia,160,false
nuburgring_mro.xml=Nuburgring,170,false
fuji_mro.xml=Fuji,150,false
korea_mro.xml=Korea,150,false
paulricard_mro.xml=Paul Ricard,180,false
india_mro.xml=India Buddh,150,false
mexico_mro.xml=Hermanos Rodriguez,240,false
jacarepagua_mro.xml=Jacarepagua,140,false
phoenix_mro.xml=Phoenix,180,false
osterreichring_mro.xml=RedBull Ring,180,false
baku_mro.xml=Baku,150,false
austin_mro.xml=Austin,160,false
jeddah_mro.xml=Jeddah,180,false
