yas_marina_mro.xml=Yas Marina,false
albert_park_mro.xml=Albert Park,true
singapura_mro.xml=Singapura,false
monza_mro.xml=Monza,false
montecarlo_mro.xml=Monte Carlo,true
interlagos_mro.xml=Interlagos,true
silverstone_mro.xml=Silverstone,false
indianapoles_mro.xml=Indianapoles,false
montreal_mro.xml=Montreal,false
magny_mro.xml=Magny-Cours,false
suzuka_mro.xml=Suzuka,false
hockenheim_mro.xml=Hockenheim,false
hockenheim6601_mro.xml=Hockenheim6601,false
spa_mro.xml=Spa-Francorchamps,false
hungaro_ring_mro.xml=Hungaro Ring,false
catalunya_mro.xml=Catalunya,true
bahrain_mro.xml=Bahrain,false
spang_mro.xml=Sepang,false
shangai_mro.xml=Shangai,false
jerez_mro.xml=Jerez,false
donington_mro.xml=Donington,false
istambul_mro.xml=Istanbul Park,false
estoril_mro.xml=Estoril,false
imola_mro.xml=Imola,false
valencia_mro.xml=Valencia,false
nuburgring_mro.xml=Nuburgring,false
fuji_mro.xml=Fuji,false
korea_mro.xml=Korea,false
paulricard_mro.xml=Paul Ricard,false
india_mro.xml=India Buddh,false
mexico_mro.xml=Hermanos Rodriguez,false
jacarepagua_mro.xml=Jacarepagua,false
phoenix_mro.xml=Phoenix,false
osterreichring_mro.xml=RedBull Ring,false
baku_mro.xml=Baku,false
austin_mro.xml=Austin,false
jeddah_mro.xml=Jeddah,false
