#Carro,Habilidade
M.Verstappen=RedBull-RB22,99
I.Hadjar=RedBull-RB22,82
L.Norris=McLaren-MCL40,96
O.Piastri=McLaren-MCL40,95
C.Leclerc=Ferrari-SF26,97
L.Hamilton=Ferrari-SF26,94
G.Russell=Mercedes-W17,95
K.Antonelli=Mercedes-W17,88
F.Alonso=AstonMartin-AMR26,93
L.Stroll=AstonMartin-AMR26,77
P.Gasly=Alpine-A526,87
F.Colapinto=Alpine-A526,82
A.Albon=Williams-FW48,89
C.Sainz=Williams-FW48,91
L.Lawson=RacingBulls-VCARB02,84
A.Lindblad=RacingBulls-VCARB02,80
E.Ocon=Haas-VF26,85
O.Bearman=Haas-VF26,83
N.Hulkenberg=Audi-R26,86
G.Bortoleto=Audi-R26,84
S.Perez=Cadillac-CF26,87
V.Bottas=Cadillac-CF26,85