#Carro,Habilidade
M.Verstappen=RedBull-RB22,92
I.Hadjar=RedBull-RB22,82
L.Norris=McLaren-MCL40,96
O.Piastri=McLaren-MCL40,95
C.Leclerc=Ferrari-SF26,95
L.Hamilton=Ferrari-SF26,97
G.Russell=Mercedes-W17,91
K.Antonelli=Mercedes-W17,98
F.Alonso=AstonMartin-AMR26,83
L.Stroll=AstonMartin-AMR26,71
P.Gasly=Alpine-A526,87
F.Colapinto=Alpine-A526,89
A.Albon=Williams-FW48,80
C.Sainz=Williams-FW48,88
L.Lawson=RacingBulls-VCARB02,78
A.Lindblad=RacingBulls-VCARB02,85
E.Ocon=Haas-VF26,77
O.Bearman=Haas-VF26,86
N.Hulkenberg=Audi-R26,85
G.Bortoleto=Audi-R26,85
S.Perez=Cadillac-CF26,77
V.Bottas=Cadillac-CF26,75