#Carro,Habilidade
M.Verstappen=RedBull-RB22,92,M.Hermann
I.Hadjar=RedBull-RB22,82,I.Hagar
L.Norris=McLaren-MCL40,91,L.Norton
O.Piastri=McLaren-MCL40,90,O.Picard
C.Leclerc=Ferrari-SF26,95,C.Leblanc
L.Hamilton=Ferrari-SF26,97,L.Harrington
G.Russell=Mercedes-W17,91,G.Roody
K.Antonelli=Mercedes-W17,98,K.Donateli
F.Alonso=AstonMartin-AMR26,83,F.Afortunado
L.Stroll=AstonMartin-AMR26,71,L.Strike
P.Gasly=Alpine-A526,87,P.Gallois
F.Colapinto=Alpine-A526,89,F.Colombino
A.Albon=Williams-FW48,80,A.Aromdee
C.Sainz=Williams-FW48,88,C.Salazar
L.Lawson=RacingBulls-VCARB02,78,L.Lawless
A.Lindblad=RacingBulls-VCARB02,85,A.Lindberg
E.Ocon=Haas-VF26,77,E.Oreux
O.Bearman=Haas-VF26,86,O.Beaverman
N.Hulkenberg=Audi-R26,85,N.Haizenberg
G.Bortoleto=Audi-R26,85,G.Borboleto
S.Perez=Cadillac-CF26,77,S.Pacheco
V.Bottas=Cadillac-CF26,75,V.Bobbas
