#Carro,Habilidade
L.Hamilton=Mercedes-W08,95,L.Harrington
V.Bottas=Mercedes-W08,85,V.Bobbas
M.Verstappen=Redbull-RB13,92,M.Hermann
D.Ricciardo=Redbull-RB13,91,D.Hypardo
S.Vettel=Ferrari-SF70H,95,S.Vesper
K.Raikkonen=Ferrari-SF70H,79,K.Raiceberg
F.Alonso=McLaren-MCL-32,86,F.Afortunado
S.Vandoorne=McLaren-MCL-32,75,S.Simons
S.Perez=Force-India-VJM-10,82,S.Pacheco
E.Ocon=Force-India-VJM-10,78,E.Oreux
M.Ericsson=Sauber-C-36,68,M.Magnusson
P.Wehrlein=Sauber-C-36,75,P.Peters
D.Kvyat=Toro-Rosso-STR12,70,D.Torpedo
C.Sainz=Toro-Rosso-STR12,79,C.Salazar
F.Massa=Williams-FW40,75,F.Mussi
L.Stroll=Williams-FW40,70,L.Strike
N.Hulkenberg=Renault-RS17,80,N.Haizenberg
J.Palmer=Renault-RS17,55,J.Johnston
R.Grosjean=Haas-VF-17,70,R.Groseille
K.Magnussen=Haas-VF-17,60,K.Kristensen
