services:
  flmane:
    image: sowbreira/flmane:latest
    container_name: flmane
    restart: unless-stopped
    ports:
      - "80:8080"
    environment:
      JDBC_URL: jdbc:mysql://db:3306/flmane?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      JDBC_USER: root
      JDBC_PASSWORD: flmane
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: flmane
      MYSQL_DATABASE: flmane
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pflmane"]
      interval: 10s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: flmane

volumes:
  mysql_data:
networks:
  default:
    ipam:
      config:
        - subnet: 10.20.0.0/24
