sonar.projectKey=br.nnpe:flmane
sonar.projectName=FlMane
sonar.projectVersion=1.0.0

sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

sonar.junit.reportPaths=target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.exclusions=**/webapp/**,**/sprites/**,**/META-INF/**,**/module-info.class
sonar.coverage.exclusions=**/webapp/**,**/sprites/**,**/META-INF/**,**/module-info.class

sonar.sourceEncoding=UTF-8
