#Carro,Habilidade
M.Verstappen=RedBull-RB20,99,M.Hermann
S.Perez=RedBull-RB20,62,S.Pacheco
L.Hamilton=Mercedes-W15,93,L.Harrington
G.Russel=Mercedes-W15,89,G.Roody
C.Leclerc=Ferrari-SF24,92,C.Leblanc
C.Sainz=Ferrari-SF24,86,C.Salazar
L.Norris=McLaren-MCL38,88,L.Norton
O.Piastri=McLaren-MCL38,87,O.Picard
L.Stroll=AstonMartin-AMR24,65,L.Strike
F.Alonso=AstonMartin-AMR24,88,F.Afortunado
P.Gasly=Alpine-A524,71,P.Gallois
E.Ocon=Alpine-A524,69,E.Oreux
A.Albon=Williams-FW46,72,A.Aromdee
F.Colapinto=Williams-FW46,85,F.Colombino
L.Lawson=VCARB-01,80,L.Lawless
Y.Tsunoda=VCARB-01,78,Y.Yoshida
V.Bottas=Kick-Sauber-C44,70,V.Bobbas
G.Zhou=Kick-Sauber-C44,60,G.Guo
N.Hulkenberg=Haas-VF-24,77,N.Haizenberg
K.Magnussen=Haas-VF-24,70,K.Kristensen
