#Carro,Habilidade
S.Vettel=Redbull-RB7,95,S.Vesper
M.Webber=Redbull-RB7,88,M.Witchell
L.Hamilton=McLaren-MP4-26,85,L.Harrington
J.Button=McLaren-MP4-26,90,J.Jenkins
F.Alonso=Ferrari-F150th,92,F.Afortunado
F.Massa=Ferrari-F150th,84,F.Mussi
N.Heidfeld=Renault-R31,77,N.Hidefill
V.Petrov=Renault-R31,75,V.Volkov
M.Schumacher=Mercedes-MGPW02,78,M.Schneider
N.Rosberg=Mercedes-MGPW02,86,N.Rosen
P.diResta=Force-India-VJM-04,79,P.Powell
A.Sutil=Force-India-VJM-04,72,A.Albrecht
K.Kobaiashi=Sauber-C-30,79,K.Kimura
S.Perez=Sauber-C-30,80,S.Pacheco
S.Buemi=Toro-Rosso-STR06,73,S.Stalder
J.Alguersuari=Toro-Rosso-STR06,70,J.Jimenez
P.Maldonado=Williams-FW33,75,P.Winwall
R.Barrichello=Williams-FW33,70,R.Velocichelli
J.Trulli=Lotus-T128,68,J.Jannuzzi
H.Kovalainen=Lotus-T128,68,H.Heikkinen
V.Liuzzi=HRT-F111,66,V.Villa
N.Karthikeyan=HRT-F111,65,N.Nair
T.Glock=Virgin-VR02,66,T.Thoma
J.d'Ambrosio=Virgin-VR02,65,J.Jacquet
