#Wed, 15 Jul 2026 22:39:54 -0300
port=80
host=localhost
versao=6.967
versaoMesAno=06-2026
idGoogle=143142801251-n0a6bc0rs03h41bt7ganklmlrokqn6te.apps.googleusercontent.com
applet=true
codeBase=

