#Sun, 12 Jul 2026 14:11:07 -0300
port=80
host=localhost
versao=6.964
versaoMesAno=06-2026
idGoogle=143142801251-n0a6bc0rs03h41bt7ganklmlrokqn6te.apps.googleusercontent.com
applet=true
codeBase=

