#Carro,Habilidade
L.Hamilton=Mercedes-W07,93,L.Harrington
N.Rosberg=Mercedes-W07,90,N.Rosen
M.Verstappen=Redbull-RB12,91,M.Hermann
D.Ricciardo=Redbull-RB12,87,D.Hypardo
S.Vettel=Ferrari-SF16,92,S.Vesper
K.Raikkonen=Ferrari-SF16,79,K.Raiceberg
F.Alonso=McLaren-MP4-31,84,F.Afortunado
J.Button=McLaren-MP4-31,78,J.Jenkins
S.Perez=Force-India-VJM-09,82,S.Pacheco
N.Hulkenberg=Force-India-VJM-09,78,N.Haizenberg
M.Ericsson=Sauber-C-35,68,M.Magnusson
F.Nasr=Sauber-C-35,75,F.Ferreira
D.Kvyat=Toro-Rosso-STR11,70,D.Torpedo
C.Sainz=Toro-Rosso-STR11,79,C.Salazar
F.Massa=Williams-FW38,75,F.Mussi
V.Bottas=Williams-FW38,90,V.Bobbas
K.Magnussen=Renault-RS16,70,K.Kristensen
J.Palmer=Renault-RS16,55,J.Johnston
P.Wehrlein=Manor-MTR5,75,P.Peters
R.Haryanto=Manor-MTR5,66,R.Ramadhan
R.Grosjean=Haas-VF-16,70,R.Groseille
E.Gutierrez=Haas-VF-16,60,E.Espinoza
