#Carro,Habilidade
G.Hill=Lotus-49B,94,G.Hall
J.Siffert=Lotus-49B,86,J.Jost
D.Hulme=McLaren-M7A,92,D.Humble
B.McLaren=McLaren-M7A,89,B.Barrett
J.Stewart=Matra-MS10,93,J.Steward
J.Beltoise=Matra-MS10,86,J.Jourdan
J.Ickx=Ferrari-312,91,J.Ichi
C.Amon=Ferrari-312,86,C.Campbell
P.Rodriguez=BRM-133,89,P.Pena
R.Attwood=BRM-133,86,R.Reid
LScarfiotti=Cooper-T86B,86,L.Leone
L.Bianchi=Cooper-T86B,86,L.Lambert
J.Surtees=Honda-302,89,J.Judge
J.Bonnier=Honda-302,86,J.Johansson
J.Rindt=Brabham-BT26,88,J.Jung
J.Brabham=Brabham-BT26,85,J.James

