#Carro,Habilidade
S.Vettel=Redbull-RB9,98,S.Vesper
M.Webber=Redbull-RB9,85,M.Witchell
F.Alonso=Ferrari-F138,90,F.Afortunado
F.Massa=Ferrari-F138,80,F.Mussi
K.Raikkonen=Lotus-E21,87,K.Raiceberg
R.Grosjean=Lotus-E21,74,R.Groseille
L.Hamilton=Mercedes-W04,87,L.Harrington
N.Rosberg=Mercedes-W04,86,N.Rosen
S.Perez=McLaren-MP4-28,80,S.Pacheco
J.Button=McLaren-MP4-28,80,J.Jenkins
P.diResta=Force-India-VJM-06,70,P.Powell
A.Sutil=Force-India-VJM-06,72,A.Albrecht
E.Gutierrez=Sauber-C-32,70,E.Espinoza
N.Hulkenberg=Sauber-C-32,75,N.Haizenberg
J.Vergne=Toro-Rosso-STR08,73,J.Jouve
D.Ricciardo=Toro-Rosso-STR08,70,D.Hypardo
P.Maldonado=Williams-FW35,74,P.Winwall
V.Bottas=Williams-FW35,70,V.Bobbas
C.Pic=Caterham-CT02,68,C.Colin
G.Garde=Caterham-CT02,68,G.Gustavsen
J.Bianchi=Marussia-MR02,83,J.Jubert
M.Chilton=Marussia-MR02,65,M.Morgan
