#Carro,Habilidade
J.Button=Brawn-BGP001,91,J.Jenkins
R.Barrichello=Brawn-BGP001,88,R.Velocichelli
G.Fisichella=Ferrari-F60,87,G.Gallo
K.Raikkonen=Ferrari-F60,89,K.Raiceberg
L.Hamilton=McLaren-MP4-24,86,L.Harrington
H.Kovalainen=McLaren-MP4-24,86,H.Heikkinen
S.Vettel=Redbull-RB5,91,S.Vesper
M.Webber=Redbull-RB5,90,M.Witchell
R.Kubica=BMW-Sauber-F1-09,85,R.Rutkowski
N.Heidfeld=BMW-Sauber-F1-09,85,N.Hidefill
F.Alonso=Renault-R29,90,F.Afortunado
R.Grosjean=Renault-R29,81,R.Groseille
J.Trulli=Toyota-TF109,88,J.Jannuzzi
T.Glock=Toyota-TF109,86,T.Thoma
N.Rosberg=Williams-FW31,88,N.Rosen
K.Nakajima=Williams-FW31,83,K.Kato
S.Buemi=Toro-Rosso-STR04,85,S.Stalder
J.Alguersuari=Toro-Rosso-STR04,84,J.Jimenez
V.Liuzzi=Force-India-VJM-02,84,V.Villa
A.Sutil=Force-India-VJM-02,86,A.Albrecht
