#Carro,Habilidade
F.Massa=Ferrari-F2008,96,F.Mussi
K.Raikkonen=Ferrari-F2008,94,K.Raiceberg
L.Hamilton=McLaren-MP4-23,95,L.Harrington
H.Kovalainen=McLaren-MP4-23,83,H.Heikkinen
R.Kubica=BMW-Sauber-F1-08,93,R.Rutkowski
N.Heidfeld=BMW-Sauber-F1-08,87,N.Hidefill
F.Alonso=Renault-R28,90,F.Afortunado
N.Piquet=Renault-R28,85,N.Pivet
N.Rosberg=Williams-FW30,85,N.Rosen
K.Nakajima=Williams-FW30,83,K.Kato
D.Coulthard=Redbull-RB4,83,D.Courtyard
M.Webber=Redbull-RB4,87,M.Witchell
J.Trulli=Toyota-TF108,83,J.Jannuzzi
T.Glock=Toyota-TF108,88,T.Thoma
S.Vettel=Toro-Rosso-STR03,86,S.Vesper
S.Bourdais=Toro-Rosso-STR03,74,S.Simon
R.Barrichello=Honda-RA108,81,R.Velocichelli
J.Button=Honda-RA108,81,J.Jenkins
G.Fisichella=Force-India-VJM-01,77,G.Gallo
A.Sutil=Force-India-VJM-01,76,A.Albrecht
