#Carro,Habilidade
L.Hamilton=Mercedes-W10,96,L.Harrington
V.Bottas=Mercedes-W10,87,V.Bobbas
S.Vettel=Ferrari-SF90,87,S.Vesper
C.Leclerc=Ferrari-SF90,92,C.Leblanc
M.Verstappen=Redbull-RB15,93,M.Hermann
A.Albon=Redbull-RB15,65,A.Aromdee
D.Ricciardo=Renault-RS19,90,D.Hypardo
N.Hulkenberg=Renault-RS19,70,N.Haizenberg
K.Magnussen=Haas-VF-19,71,K.Kristensen
R.Grosjean=Haas-VF-19,70,R.Groseille
C.Sainz=McLaren-MCL-34,79,C.Salazar
L.Norris=McLaren-MCL-34,85,L.Norton
S.Perez=RacingPoint-RP-19,74,S.Pacheco
L.Stroll=RacingPoint-RP-19,67,L.Strike
K.Raikkonen=AlfaRomeo-C-38,81,K.Raiceberg
A.Giovinazzi=AlfaRomeo-C-38,65,A.Grasso
D.Kvyat=Toro-Rosso-STR14,70,D.Torpedo
P.Gasly=Toro-Rosso-STR14,70,P.Picard
G.Russel=Williams-FW42,78,G.Roody
R.Kubica=Williams-FW42,65,R.Rutkowski
