#Carro,Habilidade
A.Senna=Lotus-98T,99,A.Silva
A.Prost=Mclaren-MP4-2C,98,A.Profe
N.Mansell=Williams-FW11,97,N.Mustache
N.Piquet=Williams-FW11,96,N.Pivet
K.Rosberg=Mclaren-MP4-2C,82,K.Rosemberg
J.Dumfries=Lotus-98T,82,J.Jarvis
S.Johansson=Ferrari-F186,87,S.Sandberg
M.Alboreto=Ferrari-F186,82,M.Marchetti
G.Berger=Benetton-B186,87,G.Bruber
T.Fabi=Benetton-B186,80,T.Testa
J.Laffite=Ligier-JS27,86,J.Julliard
R.Arnoux=Ligier-JS27,82,R.Renard
M.Brundle=Tyrrel-015,85,M.Mason
P.Streiff=Tyrrel-015,84,P.Pascal
A.Jones=Lola-THL2,85,A.Adams
P.Tambay=Lola-THL2,84,P.Prevost
R.Patrese=Brabham-BT55,84,R.Ricci
D.Warwick=Brabham-BT55,82,D.Dyer
C.Danner=Arrows-A9,76,C.Conrad
M.Surer=Arrows-A9,72,M.Marti
A.Nannini=Minardi-M186,72,A.Negri
A.Cesaris=Minardi-M186,65,A.Costa
