apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "flmane"
  namespace: "default"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "flmane"
  template:
    metadata:
      labels:
        app: "flmane"
    spec:
      containers:
        - name: "flmane"
          image: "sowbreira/flmane"
          ports:
            - containerPort: 8080  # A porta que o Tomcat escuta          
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "flmane-hpa"
  namespace: "default"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "flmane"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 1

---
apiVersion: v1
kind: Service
metadata:
  name: "flmane-service"
  namespace: "default"
spec:
  selector:
    app: "flmane"
  ports:
    - protocol: TCP
      port: 80         # A porta externa do Service
      targetPort: 8080    # A porta do contêiner
  type: LoadBalancer  # Você pode mudar para ClusterIP ou NodePort conforme necessário
