apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-mysql
spec:
  serviceName: db
  selector:
    matchLabels:
      name: mysql
  template:
    metadata:
      labels:
       name: mysql
    spec:
      containers:
        - name: container-mysql
          image: mysql:8.2.0
          ports:
            - containerPort: 3306
          resources:
            limits:
              memory: 256Mi            
          env:
            - name: MYSQL_DATABASE
              value: "flmane"
            - name: MYSQL_USER
              value: "flmane"
            - name: MYSQL_ROOT_PASSWORD
              value: "flmane"
          volumeMounts:
            - name: volume-mysql
              mountPath: /var/lib/mysql
      volumes:
       - name: volume-mysql
         persistentVolumeClaim:
           claimName: configuracao-mysql