#Carro,Habilidade
E.Fittipaldi=Lotus-72D,91,E.Fita
D.Walker=Lotus-72D,77,D.Dawes
J.Stewart=Tyrrel-04,89,J.Steward
F.Cevert=Tyrrel-04,84,F.Cereal
D.Hulme=Mclaren-M19A,88,D.Humble
P.Reverson=Mclaren-M19A,86,P.Perrault
J.Ickx=Ferrari-312B2_72,87,J.Ichi
C.Regazzoni=Ferrari-312B2_72,85,C.Macaroni
M.Hailwood=Surtess-TS9B,88,M.Miller
A.Adamich=Surtess-TS9B,82,A.Amato
R.Peterson=March-721,86,R.Robinson
C.Pace=March-721,80,C.Paz
J.Beltoise=BRM-P160,85,J.Jourdan
H.Ganley=BRM-P160,83,H.Harper
C.Amon=Matra-MS120C,87,C.Campbell
A.Merzario=Matra-MS120C,82,A.Marchetti
G.Hill=Brabham-BT34,86,G.Hall
C.Reutemann=Brabham-BT34,85,C.Realmans
N.Galli=Tecno-PA123,82,N.Negri
D.Bell=Tecno-PA123,82,D.Dawson
