#Carro,Habilidade
F.Alonso=Ferrari-F10,91,F.Afortunado
F.Massa=Ferrari-F10,89,F.Mussi
L.Hamilton=McLaren-MP4-25,90,L.Harrington
J.Button=McLaren-MP4-25,89,J.Jenkins
M.Schumacher=Mercedes-MGPW01,81,M.Schneider
N.Rosberg=Mercedes-MGPW01,88,N.Rosen
S.Vettel=Redbull-RB6,91,S.Vesper
M.Webber=Redbull-RB6,90,M.Witchell
N.Hulkenberg=Williams-FW32,81,N.Haizenberg
R.Barrichello=Williams-FW32,80,R.Velocichelli
R.Kubica=Renault-R30,89,R.Rutkowski
V.Petrov=Renault-R30,81,V.Volkov
J.Trulli=Lotus-T127,77,J.Jannuzzi
H.Kovalainen=Lotus-T127,76,H.Heikkinen
S.Buemi=Toro-Rosso-STR05,78,S.Stalder
J.Alguersuari=Toro-Rosso-STR05,79,J.Jimenez
V.Liuzzi=Force-India-VJM-03,80,V.Villa
A.Sutil=Force-India-VJM-03,83,A.Albrecht
K.Kobaiashi=Sauber-C-29,79,K.Kimura
P.delaRosa=Sauber-C-29,76,P.Pardo
B.Senna=HRT-F1,77,B.Barros
K.Chandhok=HRT-F1,75,K.Kapoor
T.Glock=Virgin-VR01,76,T.Thoma
L.diGrassi=Virgin-VR01,77,L.Lima
