#Carro,Habilidade
L.Hamilton=Mercedes-W06,98,L.Harrington
N.Rosberg=Mercedes-W06,90,N.Rosen
D.Kvyat=Redbull-RB11,80,D.Torpedo
D.Ricciardo=Redbull-RB11,88,D.Hypardo
S.Vettel=Ferrari-SF15,92,S.Vesper
K.Raikkonen=Ferrari-SF15,70,K.Raiceberg
F.Alonso=McLaren-MP4-30,85,F.Afortunado
J.Button=McLaren-MP4-30,78,J.Jenkins
S.Perez=Force-India-VJM-08,70,S.Pacheco
N.Hulkenberg=Force-India-VJM-08,78,N.Haizenberg
M.Ericsson=Sauber-C-34,70,M.Magnusson
F.Nasr=Sauber-C-34,75,F.Ferreira
M.Verstappen=Toro-Rosso-STR10,85,M.Hermann
C.Sainz=Toro-Rosso-STR10,74,C.Salazar
F.Massa=Williams-FW37,69,F.Mussi
V.Bottas=Williams-FW37,90,V.Bobbas
P.Maldonado=Lotus-E23,67,P.Winwall
R.Grosjean=Lotus-E23,70,R.Groseille
W.Stevens=Manor-MR03,66,W.Ward
R.Merhi=Manor-MR03,65,R.Rubio
