#Carro,Habilidade
L.Hamilton=Mercedes-W05,97,L.Harrington
N.Rosberg=Mercedes-W05,95,N.Rosen
S.Vettel=Redbull-RB10,80,S.Vesper
D.Ricciardo=Redbull-RB10,93,D.Hypardo
F.Alonso=Ferrari-F14T,90,F.Afortunado
K.Raikkonen=Ferrari-F14T,81,K.Raiceberg
K.Magnussen=McLaren-MP4-29,75,K.Kristensen
J.Button=McLaren-MP4-29,75,J.Jenkins
S.Perez=Force-India-VJM-07,70,S.Pacheco
A.Sutil=Force-India-VJM-07,72,A.Albrecht
E.Gutierrez=Sauber-C-33,70,E.Espinoza
N.Hulkenberg=Sauber-C-33,75,N.Haizenberg
J.Vergne=Toro-Rosso-STR09,73,J.Jouve
D.Kvyat=Toro-Rosso-STR09,74,D.Torpedo
F.Massa=Williams-FW36,69,F.Mussi
V.Bottas=Williams-FW36,90,V.Bobbas
P.Maldonado=Lotus-E22,67,P.Winwall
R.Grosjean=Lotus-E22,70,R.Groseille
K.Kobayashi=Caterham-CT04,68,K.Kimura
M.Ericsson=Caterham-CT04,73,M.Magnusson
J.Bianchi=Marussia-MR03,89,J.Jubert
M.Chilton=Marussia-MR03,65,M.Morgan
