#Carro,Habilidade
E.Fittipaldi=Mclaren-M23,95,E.Fita
D.Hulme=Mclaren-M23,85,D.Humble
C.Regazzoni=Ferrari-312B3,94,C.Macaroni
N.Lauda=Ferrari-312B3,93,N.Lambda
J.Scheckter=Tyrrel-007,94,J.Jansen
P.Depailler=Tyrrel-007,86,P.Petit
R.Peterson=Lotus-76,92,R.Robinson
J.Ickx=Lotus-76,86,J.Ichi
C.Reutemann=Brabham-BT44,91,C.Realmans
C.Pace=Brabham-BT44,86,C.Paz
J.Beltoise=BRM-P201,85,J.Jourdan
H.Pescarolo=BRM-P201,78,H.Henry
J.Jarier=Shadow-DN3,84,J.Janvier
T.Pryce=Shadow-DN3,78,T.Pride
H.Stuck=March-741,84,H.Hartmann
V.Brambilla=March-741,83,V.Vitale
A.Merzario=Iso_Williams-FW,86,A.Marchetti
T.Belso=Iso_Williams-FW,78,T.Toth
D.Quester=Surtess-TS16,75,D.Dietrich
D.Bell=Surtess-TS16,75,D.Dawson
M.Wilds=Ensign-N174,75,M.Mercer
L.Kinnunen=Ensign-N174,75,L.Laine
