#Carro,Habilidade
A.Senna=Mclaren-MP4-4,99,A.Silva
A.Prost=Mclaren-MP4-4,98,A.Profe
N.Mansell=Williams-FW12,97,N.Mustache
N.Piquet=Lotus-100T,96,N.Pivet
G.Berger=Ferrari-F187-88C,87,G.Bruber
M.Alboreto=Ferrari-F187-88C,82,M.Marchetti
T.Boutsen=Benetton-B188,74,T.Thys
A.Nannini=Benetton-B188,83,A.Negri
S.Nakajima=Lotus-100T,72,S.Sato
D.Warwick=Arrows-A10B,86,D.Dyer
E.Cheever=Arrows-A10B,83,E.Edwards
R.Patrese=Williams-FW12,84,R.Ricci
J.Palmer=Tyrrel-017,75,J.Johnston
J.Bailey=Tyrrel-017,82,J.Jackson
P.Martini=Minardi-M188,86,P.Piras
L.Perez=Minardi-M188,82,L.Lopez
A.Caffi=Dallara-F188,73,A.Conti
S.Modena=Dallara-F188,72,S.Serra
S.Johansson=Ligier-JS31,83,S.Sandberg
R.Arnoux=Ligier-JS31,82,R.Renard
P.Streiff=AGS-JH22,83,P.Pascal
N.Larini=AGS-JH22,82,N.Nardi
