#Carro,Habilidade
A.Senna=Lotus-99T,99,A.Silva
A.Prost=McLaren-MP4-3,98,A.Profe
N.Mansell=Williams-FW11B,97,N.Mustache
N.Piquet=Williams-FW11B,96,N.Pivet
S.Johansson=McLaren-MP4-3,83,S.Sandberg
S.Nakajima=Lotus-99T,82,S.Sato
G.Berger=Ferrari-F187,86,G.Bruber
M.Alboreto=Ferrari-F187,83,M.Marchetti
T.Boutsen=Benetton-B187,74,T.Thys
T.Fabi=Benetton-B187,83,T.Testa
J.Palmer=Tyrrell-DG016,85,J.Johnston
P.Streiff=Tyrrell-DG016,83,P.Pascal
E.Cheever=Arrows-A10,75,E.Edwards
D.Warwick=Arrows-A10,82,D.Dyer
A.Cesaris=Brabham-BT56,75,A.Costa
S.Modena=Brabham-BT56,70,S.Serra
P.Alliot=Lola-LC87,85,P.Perrin
Y.Dalmas=Lola-LC87,80,Y.Ybert
M.Brundle=Zakspeed-861,83,M.Mason
C.Danner=Zakspeed-861,76,C.Conrad
R.Arnoux=Ligier-JS29,85,R.Renard
P.Ghinzani=Ligier-JS29,70,P.Pellegrini
A.Nannini=Minardi-M187,83,A.Negri
A.Campos=Minardi-M187,73,A.Aguirre
