#Carro,Habilidade
F.Massa=Ferrari-F2007,96,F.Mussi
K.Raikkonen=Ferrari-F2007,94,K.Raiceberg
F.Alonso=McLaren-MP4-22,95,F.Afortunado
L.Hamilton=McLaren-MP4-22,94,L.Harrington
R.Kubica=BMW-Sauber-F1-07,88,R.Rutkowski
N.Heidfeld=BMW-Sauber-F1-07,89,N.Hidefill
H.Kovalainen=Renault-R27,84,H.Heikkinen
G.Fisichella=Renault-R27,86,G.Gallo
A.Wurz=Williams-FW29,88,A.Aigner
N.Rosberg=Williams-FW29,89,N.Rosen
R.Schumacher=Toyota-TF107,81,R.Schneider
J.Trulli=Toyota-TF107,88,J.Jannuzzi
M.Webber=Redbull-RB3,82,M.Witchell
D.Coulthard=Redbull-RB3,80,D.Courtyard
S.Vettel=Toro-Rosso-STR02,85,S.Vesper
V.Liuzzi=Toro-Rosso-STR02,79,V.Villa
R.Barrichello=Honda-RA107,81,R.Velocichelli
J.Button=Honda-RA107,82,J.Jenkins
S.Yamamoto=Spyker-F8-VII,77,S.Shimizu
A.Sutil=Spyker-F8-VII,76,A.Albrecht
T.Sato=Super-Aguri-SA06,78,T.Takahashi
A.Davidson=Super-Aguri-SA06,77,A.Allen
