#Carro,Habilidade
R.Arnoux=Ferrari-126C3,82,R.Renard
P.Tambay=Ferrari-126C3,84,P.Prevost
A.Prost=Renault-RE40,98,A.Profe
E.Cheever=Renault-RE40,75,E.Edwards
N.Piquet=Brabham-BT52,96,N.Pivet
R.Patrese=Brabham-BT52,85,R.Ricci
K.Rosberg=Williams-FW08C,82,K.Rosemberg
J.Laffite=Williams-FW08C,86,J.Julliard
J.Watson=Mclaren-MP4-1C,74,J.Jarman
N.Lauda=Mclaren-MP4-1C,93,N.Lambda
M.Baldi=AlfaRomeo-183T,61,M.Moretti
A.Cesaris=AlfaRomeo-183T,65,A.Costa
D.Sullivan=Tyrrel-012,73,D.Daniels
M.Alboreto=Tyrrel-012,82,M.Marchetti
B.Giacomelli=Toleman-TG183,66,B.Bruno
D.Warwick=Toleman-TG183,82,D.Dyer
N.Mansell=Lotus-92,97,N.Mustache
E.Angelis=Lotus-92,69,E.Esposito
T.Boutsen=Arrows-A6,74,T.Thys
M.Surer=Arrows-A6,72,M.Marti
J.Jarier=Ligier-JS21,66,J.Janvier
R.Boesel=Ligier-JS21,61,R.Rocha
