#Carro,Habilidade
L.Hamilton=Mercedes-W09,95,L.Harrington
S.Vettel=Ferrari-SF71H,94,S.Vesper
M.Verstappen=Redbull-RB14,93,M.Hermann
D.Ricciardo=Redbull-RB14,90,D.Hypardo
F.Alonso=McLaren-MCL-33,81,F.Afortunado
C.Leclerc=Sauber-C-37,86,C.Leblanc
V.Bottas=Mercedes-W09,85,V.Bobbas
N.Hulkenberg=Renault-RS18,80,N.Haizenberg
K.Raikkonen=Ferrari-SF71H,79,K.Raiceberg
C.Sainz=Renault-RS18,78,C.Salazar
E.Ocon=Force-India-VJM-11,77,E.Oreux
P.Gasly=Toro-Rosso-STR13,75,P.Picard
K.Magnussen=Haas-VF-18,75,K.Kristensen
S.Perez=Force-India-VJM-11,74,S.Pacheco
S.Vandoorne=McLaren-MCL-33,73,S.Simons
R.Grosjean=Haas-VF-18,70,R.Groseille
M.Ericsson=Sauber-C-37,68,M.Magnusson
B.Hartley=Toro-Rosso-STR13,66,B.Baker
L.Stroll=Williams-FW41,67,L.Strike
S.Sirotkin=Williams-FW41,65,S.Sokolov
