#Carro,Habilidade
M.Schumacher=Ferrari-F2003GA,99,M.Schneider
R.Barrichello=Ferrari-F2003GA,91,R.Velocichelli
K.Raikkinen=McLaren-MP4-17D,94,K.Raiceberg
D.Coulthard=McLaren-MP4-17D,89,D.Courtyard
J.Montoya=Williams-FW25,92,J.Montebate
R.Schumacher=Williams-FW25,90,R.Schneider
F.Alonso=Renault-R23,90,F.Afortunado
J.Trulli=Renault-R23,88,J.Jannuzzi
J.Button=BAR-005,86,J.Jenkins
J.Villeneuve=BAR-005,80,J.Joyal
M.Webber=Jaguar-R4,87,M.Witchell
J.Wilson=Jaguar-R4,80,J.Jephson
H.Frentzen=Sauber-C22,85,H.Hoffmann
N.Heidfeld=Sauber-C22,82,N.Hidefill
G.Fisichella=Jordan-EJ13,85,G.Gallo
R.Firman=Jordan-EJ13,80,R.Reeves
C.Matta=Toyota-TF103,84,C.Carvalho
O.Panis=Toyota-TF103,82,O.Olivier
J.Verstappen=Minardi-PS03,78,J.Janssen
N.Kiesa=Minardi-PS03,78,N.Nielsen
