#Carro,Habilidade
A.Senna=Mclaren-MP4_5B,99,A.Silva
A.Prost=Ferrari-F1641,98,A.Profe
N.Mansell=Ferrari-F1641,97,N.Mustache
G.Berger=Mclaren-MP4_5B,90,G.Bruber
N.Piquet=Benetton-B190,94,N.Pivet
R.Moreno=Benetton-B190,89,R.Bronse
T.Boutsen=Williams-FW13B,74,T.Thys
R.Patrese=Williams-FW13B,84,R.Ricci
J.Alesi=Tyrrel-019,89,J.Joly
S.Nakajima=Tyrrel-019,86,S.Sato
A.Suzuki=Lola-LC90,84,A.Aoki
E.Bernard=Lola-LC90,84,E.Etienne
I.Capelli=LeytonHouse-CG901,86,I.Isola
M.Gugelmin=LeytonHouse-CG901,82,M.Machado
D.Warwick=Lotus-102,84,D.Dyer
M.Donnely=Lotus-102,77,M.Mills
A.Caffi=Arrows-A11,83,A.Conti
M.Alboreto=Arrows-A11,77,M.Marchetti
S.Modena=Brabham-BT58,84,S.Serra
D.Brabham=Brabham-BT58,77,D.Dunn
P.Martini=Minardi-M190,77,P.Piras
G.Morbidelli=Minardi-M190,77,G.Greco
