#Carro,Habilidade
S.Vettel=Redbull-RB8,92,S.Vesper
M.Webber=Redbull-RB8,88,M.Witchell
L.Hamilton=McLaren-MP4-27,89,L.Harrington
J.Button=McLaren-MP4-27,88,J.Jenkins
F.Alonso=Ferrari-F2012,92,F.Afortunado
F.Massa=Ferrari-F2012,80,F.Mussi
K.Raikkonen=Lotus-E20,77,K.Raiceberg
R.Grosjean=Lotus-E20,75,R.Groseille
M.Schumacher=Mercedes-MGPW03,78,M.Schneider
N.Rosberg=Mercedes-MGPW03,86,N.Rosen
P.diResta=Force-India-VJM-05,70,P.Powell
N.Hulkenberg=Force-India-VJM-05,72,N.Haizenberg
K.Kobaiashi=Sauber-C-31,79,K.Kimura
S.Perez=Sauber-C-31,82,S.Pacheco
J.Vergne=Toro-Rosso-STR07,73,J.Jouve
D.Ricciardo=Toro-Rosso-STR07,70,D.Hypardo
P.Maldonado=Williams-FW34,82,P.Winwall
B.Senna=Williams-FW34,70,B.Barros
V.Petrov=Caterham-CT01,68,V.Volkov
H.Kovalainen=Caterham-CT01,68,H.Heikkinen
P.delaRosa=HRT-F112,66,P.Pardo
N.Karthikeyan=HRT-F112,65,N.Nair
T.Glock=Marussia-MR01,66,T.Thoma
C.Pic=Marussia-MR01,65,C.Colin
