#Carro,Habilidade
A.Senna=Mclaren-MP4_8,99,A.Silva
A.Prost=Williams-FW15C,98,A.Profe
D.Hill=Williams-FW15C,89,D.Hall
M.Hakkinen=Mclaren-MP4_8,89,M.Hanninen
M.Schumacher=Benetton-B193,90,M.Schneider
R.Patrese=Benetton-B193,88,R.Ricci
J.Alesi=Ferrari-F93A,87,J.Joly
G.Berger=Ferrari-F93A,86,G.Bruber
M.Brundle=Ligier-JS39,88,M.Mason
M.Blundell=Ligier-JS39,87,M.Marshall
J.Herbert=Lotus-107B,88,J.Jennings
A.Zanardi=Lotus-107B,85,A.Zanetti
K.Wendlinger=Sauber-C12,86,K.Kogler
J.Jarvilehto=Sauber-C12,85,J.Jarvinen
C.Fittipaldi=Minardi-M193,88,C.Fita
F.Barbazza=Minardi-M193,82,F.Ferrara
A.Cesaris=Tyrrel-YM21,86,A.Costa
U.Katayama =Tyrrel-YM21,79,U.Ueda
P.Alliot=Larrousse-LH93,84,P.Perrin
E.Comas=Larrousse-LH93,82,E.Emery
R.Barrichello=Jordan-193,88,R.Velocichelli
E.Irvine=Jordan-193,87,E.Ellis
L.Badoer=Lola-T93_30,79,L.Longo
M.Alboreto=Lola-T93_30,79,M.Marchetti
